const state={questions:[],current:null,selected:null,submitted:false,mode:'all',year:'all',subject:'all',search:'',queue:[],queueIndex:0,stats:{byId:{},today:{date:'',answered:0,correct:0}}};
const $=id=>document.getElementById(id);
function dateKey(){return new Date().toISOString().slice(0,10)}
function today(){if(!state.stats.today||state.stats.today.date!==dateKey())state.stats.today={date:dateKey(),answered:0,correct:0}}
function save(){try{localStorage.setItem('upscWebState',JSON.stringify({stats:state.stats,settings:{mode:state.mode,year:state.year,subject:state.subject,search:state.search}}))}catch{}}
function clean(s){return String(s||'').replace(/\u00ad/g,'').replace(/(?<=\w)-\s*\n\s*(?=\w)/g,'').replace(/[ \t]*\n[ \t]*/g,' ').replace(/\s{2,}/g,' ').trim()}
function matches(q){if(state.year!=='all'&&String(q.year)!==state.year)return false;if(state.subject!=='all'&&(q.subject||'General Studies')!==state.subject)return false;if(state.search){const h=(q.question+' '+q.options.join(' ')+' '+(q.explanation||'')).toLowerCase();if(!h.includes(state.search.toLowerCase()))return false}const r=state.stats.byId[q.id]||{};if(state.mode==='mistakes'&&!(r.wrongs>0))return false;if(state.mode==='bookmarks'&&!r.bookmarked)return false;return true}
function rebuild(){let p=state.questions.filter(matches);for(let i=p.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[p[i],p[j]]=[p[j],p[i]]}state.queue=p;state.queueIndex=0}
function next(){if(!state.queue.length){state.current=null;render();return}if(state.queueIndex>=state.queue.length)rebuild();state.current=state.queue[state.queueIndex++];state.selected=null;state.submitted=false;render()}
function choose(i){if(state.submitted)return;state.selected=i;[...$('options').children].forEach((b,n)=>b.classList.toggle('selected',n===i));$('check').disabled=false}
function bookmark(){if(!state.current)return;const r=state.stats.byId[state.current.id] ||= {attempts:0,correct:0,wrongs:0,bookmarked:false};r.bookmarked=!r.bookmarked;save();render()}
function answer(){if(!state.current||state.selected===null||state.submitted)return;const q=state.current,ok=state.selected===q.answer,r=state.stats.byId[q.id] ||= {attempts:0,correct:0,wrongs:0,bookmarked:false};r.attempts++;ok?r.correct++:r.wrongs++;today();state.stats.today.answered++;if(ok)state.stats.today.correct++;state.submitted=true;save();render()}
function renderQuestion(){const q=state.current;if(!q)return;const r=state.stats.byId[q.id]||{};$('qYear').textContent=q.year;$('qSubject').textContent=q.subject||'General Studies';$('qIndex').textContent=`Question ${state.queueIndex}`;$('question').textContent=clean(q.question);$('options').innerHTML='';q.options.forEach((txt,i)=>{const b=document.createElement('button');b.className='qopt';b.innerHTML=`<span class="qletter">${String.fromCharCode(65+i)}</span><span class="qtext"></span>`;b.querySelector('.qtext').textContent=clean(txt);if(!state.submitted)b.addEventListener('click',()=>choose(i));if(state.submitted){b.disabled=true;if(i===q.answer)b.classList.add('correct');if(i===state.selected&&i!==q.answer)b.classList.add('wrong')}else if(i===state.selected)b.classList.add('selected');$('options').appendChild(b)});$('bookmark').textContent=r.bookmarked?'★':'☆';$('bookmark').classList.toggle('saved',!!r.bookmarked);$('check').hidden=state.submitted;$('check').disabled=state.selected===null||state.submitted;$('next').hidden=!state.submitted;$('feedback').hidden=!state.submitted;if(state.submitted){const ok=state.selected===q.answer;$('feedbackTitle').textContent=ok?'✓ Correct':'✗ Incorrect';$('feedbackTitle').style.color=ok?'var(--success)':'var(--danger)';$('feedbackAnswer').textContent=`Correct answer: ${String.fromCharCode(65+q.answer)}`;$('feedbackText').textContent=clean(q.explanation||'Explanation was not available in the supplied source for this question.')}}
function renderToday(){if(!state.questions.length)return;let seed=0;for(const c of dateKey())seed=(seed*31+c.charCodeAt(0))>>>0;const q=state.questions[seed%state.questions.length];$('heroYear').textContent=q.year;$('heroSubject').textContent=q.subject||'General Studies';$('heroQuestion').textContent=clean(q.question);$('heroOptions').innerHTML=q.options.map((x,i)=>`<div class="mini-option">${String.fromCharCode(65+i)}. ${clean(x)}</div>`).join('');$('heroSolve').onclick=()=>document.getElementById('practice').scrollIntoView({behavior:'smooth'})}
function renderStats(){today();const a=state.stats.today.answered,c=state.stats.today.correct;$('sToday').textContent=a;$('sAcc').textContent=a?`${Math.round(c/a*100)}%`:'—';$('sMistakes').textContent=Object.values(state.stats.byId).filter(r=>r.wrongs>0).length;$('sBookmarks').textContent=Object.values(state.stats.byId).filter(r=>r.bookmarked).length;const acc={};state.questions.forEach(q=>{const s=q.subject||'General Studies';(acc[s] ||= {a:0,c:0});const r=state.stats.byId[q.id];if(r){acc[s].a+=r.attempts||0;acc[s].c+=r.correct||0}});$('bars').innerHTML=Object.entries(acc).filter(([,r])=>r.a).sort((a,b)=>b[1].a-a[1].a).slice(0,7).map(([s,r])=>{const p=Math.round(r.c/r.a*100);return `<div class="progress-row"><div class="progress-name">${s}</div><div class="bar"><i style="width:${p}%"></i></div><div class="pct">${p}%</div></div>`}).join('')||'<div style="color:var(--muted);font-size:10px">Answer a few questions to see subject accuracy here.</div>'; $('count').textContent=state.questions.length.toLocaleString('en-IN')}
function renderBrowse(){const data=[['Polity','Governance, Constitution, Parliament and more',q=>q.subject==='Polity'],['Environment and Ecology','Climate, biodiversity, ecosystems and conservation',q=>q.subject==='Environment and Ecology'],['Indian Economy','Banking, fiscal policy, markets and development',q=>q.subject==='Indian Economy'],['History','Ancient, medieval and modern history',q=>['Ancient and Medieval History','Modern History'].includes(q.subject)]];$('browse').innerHTML=data.map(([s,d,test])=>{const n=state.questions.filter(test).length;return `<button class="browse-card" data-s="${s}"><div class="num">${n}</div><h3>${s}</h3><p>${d}</p></button>`}).join('');document.querySelectorAll('.browse-card').forEach(b=>b.onclick=()=>{state.subject=b.dataset.s==='History'?'all':b.dataset.s;$('subject').value=state.subject;state.mode='all';rebuild();next();document.getElementById('practice').scrollIntoView({behavior:'smooth'})})}
function setModes(){document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode))}
function render(){today();$('card').hidden=!state.current;$('empty').hidden=!!state.current;if(state.current)renderQuestion();renderToday();renderStats();setModes()}
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
async function init(){const qs=await fetch('data/questions.json').then(r=>r.json());state.questions=qs.filter(q=>Array.isArray(q.options)&&q.options.length===4&&Number.isInteger(q.answer));let saved={};try{saved=JSON.parse(localStorage.getItem('upscWebState')||'{}')}catch{}state.stats=saved.stats||state.stats;state.mode=saved.settings?.mode||'all';state.year=saved.settings?.year||'all';state.subject=saved.settings?.subject||'all';state.search=saved.settings?.search||'';today();const years=[...new Set(state.questions.map(q=>q.year).filter(Number.isFinite))].sort((a,b)=>b-a);years.forEach(y=>{const o=document.createElement('option');o.value=y;o.textContent=y;$('year').appendChild(o)});[...new Set(state.questions.map(q=>q.subject||'General Studies'))].sort().forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;$('subject').appendChild(o)});$('year').value=state.year;$('subject').value=state.subject;$('search').value=state.search;renderBrowse();rebuild();next();
$('year').onchange=()=>{state.year=$('year').value;save();rebuild();next()};$('subject').onchange=()=>{state.subject=$('subject').value;save();rebuild();next()};$('search').oninput=()=>{state.search=$('search').value.trim();save();rebuild();next()};$('clear').onclick=$('clearEmpty').onclick=()=>{state.year='all';state.subject='all';state.search='';state.mode='all';$('year').value='all';$('subject').value='all';$('search').value='';save();rebuild();next()};document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;save();rebuild();next()});$('bookmark').onclick=bookmark;$('check').onclick=answer;$('next').onclick=next;
$('chromeLink').onclick=e=>{e.preventDefault();toast('Chrome Web Store link will be added after approval.')};$('edgeLink').onclick=e=>{e.preventDefault();toast('Edge Add-ons link will be added after approval.')};$('mobileMenu').onclick=()=>{const n=$('nav');n.dataset.open=n.dataset.open==='1'?'0':'1'};document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;if(['INPUT','SELECT'].includes(document.activeElement?.tagName))return;if(state.submitted&&e.key==='Enter'){e.preventDefault();next();return}if(state.submitted)return;const k=e.key.toLowerCase();if('abcd'.includes(k)){choose(k.charCodeAt(0)-97);e.preventDefault()}if(e.key==='Enter'){answer();e.preventDefault()}})}
init().catch(e=>{console.error(e);$('question').textContent='Could not load the PYQ database. Please refresh the page.'});